### ISSUE TITLE
No such file or directory: outputdir/.npy.npy

### ISSUE THREAD

**Issue by AlexanderAntropov** [AIforGreatGood/charge3net#9]
### Description

When running the script `convert_chgcar_dir_to_pkl_dir.py`, I encounter a `FileNotFoundError`. The error occurs because the script tries to access a `.npy` file that does not exist in the output directory.

#### Command Used:
```bash
python scripts/convert_chgcar_dir_to_pkl_dir.py --input ./vasp_tests/Mo3Cr/ --output ./vasp_tests/Mo3Cr_E3/

`0it [00:00, ?it/s]('CHGCAR',)
1it [00:00,  6.05it/s]
  0%|                                                                                           | 0/2 [00:00<?, ?it/s]
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "/path/to/python/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/path/to/write_mp_probe_count_file.py", line 17, in count_elements_in_numpy_file
    arr = np.load(file_path)
  File "/path/to/numpy/lib/npyio.py", line 427, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: 'vasp_tests/Mo3Cr_E3/.npy.npy'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/path/to/convert_chgcar_dir_to_pkl_dir.py", line 63, in <module>
    count_elements_in_numpy_files(file_list_path=filelist_file, workers=1)
  File "/path/to/write_mp_probe_count_file.py", line 41, in count_elements_in_numpy_files
    results = list(tqdm(p.imap(count_elements_in_numpy_file, file_list), total=len(file_list)))
  File "/path/to/tqdm/std.py", line 1181, in __iter__
    for obj in iterable:
  File "/path/to/python/multiprocessing/pool.py", line 873, in next
    raise value
FileNotFoundError: [Errno 2] No such file or directory: 'vasp_tests/Mo3Cr_E3/.npy.npy'`

Would you be able to advise on resolving this issue?

**Comment by teddykoker** [comment]
Hi @AlexanderAntropov, can you share the structure of the input directory you are running on and perhaps the content of the filelist.txt that was generated? It looks like it may have converted the files okay but ran into some issue during the [`count_elements_in_numpy_files`](https://github.com/AIforGreatGood/charge3net/blob/main/scripts/convert_chgcar_dir_to_pkl_dir.py#L67) step. I could see this occuring if somehow an incorrect filename was written to the filelist.

**Comment by AlexanderAntropov** [comment]
> Hi @AlexanderAntropov, can you share the structure of the input directory you are running on and perhaps the content of the filelist.txt that was generated? It looks like it may have converted the files okay but ran into some issue during the [`count_elements_in_numpy_files`](https://github.com/AIforGreatGood/charge3net/blob/main/scripts/convert_chgcar_dir_to_pkl_dir.py#L67) step. I could see this occuring if somehow an incorrect filename was written to the filelist.

Hi, @teddykoker! Thank you very much for quick reply!

I have ~/charge3Net directory which contains all files and folders from GitHub.
In the ~/charge3Net/vasp_tests/Mo3Cr I have all vasp files from self-consisted successful run:

```
AECCAR0  CONTCAR    KPOINTS  OUTCAR  POTCAR  vaspout.h5   XDATCAR
AECCAR1  CHG         DOSCAR    IBZKPT        LOCPOT   PCDAT   REPORT  vasprun.xml
AECCAR2  CHGCAR      EIGENVAL  INCAR         OSZICAR  POSCAR  run.sh  WAVECAR
```

After running 
`python scripts/convert_chgcar_dir_to_pkl_dir.py --input ./vasp_tests/Mo3Cr/ --output ./vasp_tests/Mo3Cr_E3/`

I have two files 
`_atoms.pkl  filelist.txt`
in ~/chargE3net/vasp_tests/Mo3Cr_E3

In filelist.txt there is only one row:
`.npy`

**Comment by teddykoker** [comment]
Ah, thank you for the additional information. The `convert_chgcar_dir_to_pkl_dir.py` expects multiple directories, each with CHGCARs in them, for example if you had:

```
./vasp_tests/A/CHGCAR
./vasp_tests/B/CHGCAR
./vasp_tests/B/CHGCAR
```

And you used `vasp_tests` as your input directory, it would write files `A.npy`, `B.npy`, `C.npy` for the charge density. In your case above there are no middle directories so the code runs into issues with the filenames.

Since you only have one material, you should be able to use `scripts/convert_chgcar_to_pkl.py` instead of the directory version, which would look like:

```bash
python scripts/convert_chgcar_dir_to_pkl_dir.py --chgcar_file ./vasp_tests/Mo3Cr/CHGCAR --output ./vasp_tests/Mo3Cr_E3/
```
I would delete `vasp_tests/Mo3Cr_E3/` first to make sure the existing files don't cause any issues. Let me know if this works or if you continue to have any issues!
